- name: "Sending SMS Notification"
  on:
    push:
      branches:
        - main

  jobs:
    send-sms:
      name: "Twilio Notification"
      runs-on: ubuntu-latest
      steps:
        - uses: twilio-labs/actions-sms@v1
          with:
            fromPhoneNumber: "+12055830423"
            toPhoneNumber: "+9779845977786"
            message: "API keys are revokable credentials for the Twilio API."
            env:
            TWILIO_ACCOUNT_SID: ACc994e316f9eede3c165df8929de50d47
            TWILIO_API_KEY: SK0e798e3a2851d7e9350df9ba8f334d44
            TWILIO_API_SECRET: IIkSDrowlOsMEfvQDduIfmHCFENRLwRj
